### ISSUE TITLE
Rework the job flow to include a preview step

### ISSUE THREAD

**Issue by creuter** [thoughtbot/community#27]
![landing](https://cloud.githubusercontent.com/assets/2317604/15259804/5f92fae6-1921-11e6-8c23-608413d6c9ee.png)

![job-new](https://cloud.githubusercontent.com/assets/2317604/15259813/668053c6-1921-11e6-93df-8d76e6faaf4f.png)

![job-preview](https://cloud.githubusercontent.com/assets/2317604/15259808/62eca20a-1921-11e6-9196-095af9df2daf.png)

![job-secret](https://cloud.githubusercontent.com/assets/2317604/15259816/6d4cd7ba-1921-11e6-8d3b-aa84f8aa3ced.png)

**Comment by drapergeek** [comment]
This is ready for design work
