### ISSUE TITLE
Mockups

### ISSUE THREAD

**Issue by drapergeek** [thoughtbot/community#4]
I wanted to put these up so they were easy to reference.

![desktop hd copy 2](https://cloud.githubusercontent.com/assets/89965/13196717/8bdfdb46-d7a4-11e5-8ef2-5e402b171ee4.png)
![desktop hd copy 3](https://cloud.githubusercontent.com/assets/89965/13196718/8bedf4d8-d7a4-11e5-8daf-58bba28ed74e.png)
![desktop hd copy 4](https://cloud.githubusercontent.com/assets/89965/13196720/8bf09aa8-d7a4-11e5-84f5-15f45642da82.png)
![desktop hd copy 5](https://cloud.githubusercontent.com/assets/89965/13196719/8bf08f86-d7a4-11e5-8227-84fd9c793a59.png)
![desktop hd copy 6](https://cloud.githubusercontent.com/assets/89965/13196721/8bf12d24-d7a4-11e5-9ed0-6ca5a4bc9291.png)
![desktop hd copy](https://cloud.githubusercontent.com/assets/89965/13196722/8bf2cff8-d7a4-11e5-9b03-75deaafca9dd.png)

**Comment by creuter** [comment]
Closing this, it's polluting waffle.io
