### ISSUE TITLE
Show members on the members index

### ISSUE THREAD

**Issue by creuter** [thoughtbot/community#7]
@drapergeek Could I get some help wiring up members on `cr-members`?

![screen shot 2016-03-04 at 8 31 22 am](https://cloud.githubusercontent.com/assets/2317604/13528402/c4953618-e1e3-11e5-9a6a-db7a112d50c7.png)

We can pull out the gravatar, twitter, dribbble, and available for hire bits for later PRs if you think that's more appropriate.

**Comment by toobulkeh** [comment]
is that image from gravatar?

**Comment by creuter** [comment]
@toobulkeh  Just a placeholder for now, but I'd eventually to like to hook up gravatar. I grabbed it from uifaces.com

**Comment by drapergeek** [comment]
Fixed in 27a65641ce155c6f33098210f5bfdb1257c88bc3

Only includes the name and title for now.
